python generate_coco.py -p "A children's book page illustration of Hello friends" -o "./image2/Page_01.png"
python generate_coco.py -p "A children's book page illustration of this book is all about body positivity that means we're going to talk about how awesome it is to have a body no matter what shape or size it is" -o "./image2/Page_02.png"
python generate_coco.py -p "A children's book page illustration of There's no one right way to have a body" -o "./image2/Page_03.png"
python generate_coco.py -p "A children's book page illustration of Every body is different and thats what makes them so special" -o "./image2/Page_04.png"
python generate_coco.py -p "A children's book page illustration of Your body is amazing" -o "./image2/Page_05.png"
python generate_coco.py -p "A children's book page illustration of It can do so many things and its always changing and growing" -o "./image2/Page_06.png"
python generate_coco.py -p "A children's book page illustration of You dont have to be perfect to be beautiful You are beautiful just the way you are" -o "./image2/Page_07.png"
python generate_coco.py -p "A children's book page illustration of Everyone is different and that's okay! You don't have to look or act like anyone else." -o "./image2/Page_08.png"
python generate_coco.py -p "A children's book page illustration of You can be whoever you want to be" -o "./image2/Page_09.png"
python generate_coco.py -p "A children's book page illustration of You are in control of your body You can do whatever you want with it and you should be proud of it" -o "./image2/Page_10.png"
python generate_coco.py -p "A children's book page illustration of You are worth so much no matter what your body looks like" -o "./image2/Page_11.png"
python generate_coco.py -p "A children's book page illustration of You have the power to do great things and you should never forget that" -o "./image2/Page_12.png"
python ".\upscale_dir.py" ".\image2\"