python generate_coco.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_01_coco.png"
python generate_coco.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_02_coco.png"
python generate_coco.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_03_coco.png"
python generate_coco.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_04_coco.png"
python generate_coco.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_05_coco.png"
python generate.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_01.png"
python generate.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_02.png"
python generate.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_03.png"
python generate.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_04.png"
python generate.py -p "A painting of innovation" -o "./image2/PaintingSpiritInnovation_05.png"
python ".\upscale_dir.py" ".\image2\"